import { Router, type IRouter } from "express";
import healthRouter from "./health";
import eventRouter from "./event";
import asoebiRouter from "./asoebi";
import adminAsoebiRouter from "./admin-asoebi";
import rsvpsRouter from "./rsvps";
import checkoutRouter from "./checkout";
import adminRouter from "./admin";
import authRouter from "./auth";
import webhooksRouter from "./webhooks";
import deliveryRouter from "./delivery";
import notificationsRouter from "./notifications";
import siteSettingsRouter from "./site-settings";
import spotifyRouter from "./spotify";
import uploadsRouter from "./uploads";
import rsvpFormCopyRouter from "./rsvp-form-copy";
import campaignsRouter from "./campaigns";
import checkInRouter from "./check-in";

const router: IRouter = Router();

router.use(healthRouter);
router.use(eventRouter);
router.use(asoebiRouter);
router.use(adminAsoebiRouter);
router.use(rsvpsRouter);
router.use(checkoutRouter);
router.use(adminRouter);
router.use(authRouter);
router.use(webhooksRouter);
router.use(deliveryRouter);
router.use(notificationsRouter);
router.use(siteSettingsRouter);
router.use(spotifyRouter);
router.use(uploadsRouter);
router.use(rsvpFormCopyRouter);
router.use(campaignsRouter);
router.use(checkInRouter);

export default router;
